### ISSUE TITLE
Hilfe-Seite

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#105]
Implementierung der Hilfe Seite. Aus Mangel an Text einfach ein Link auf: http://www.amazon.de/Basiswissen-Mathematik-Statistik-Operations-Wirtschaftswissenschaftler/dp/3486596640

**Comment by dyslexicT** [comment]
MEINS

**Comment by Schtani** [comment]
Impl. im RootController z.B.: via http://stackoverflow.com/questions/16604341/how-can-i-open-the-default-system-browser-from-a-java-fx-application
