### ISSUE TITLE
Tab 1: Umsortierung der Werte bei zu vielen Eingaben desselben Wertes

### ISSUE THREAD

**Issue by Bawama** [Schtani/Stichprobe#12]
in der Häufigkeitstabelle der erfassten werte werden die Werte umsortiert, wenn man ein- und denselben wert mehrmals hinzufügt (ca. 20 mal und mehr...)

**Comment by Schtani** [comment]
Bei setData() wird die sortierung der rechten Tabelle verworfen.

**Comment by Schtani** [comment]
Fixed with merge. Bitte @Bawama  nachtesten

**Comment by Bawama** [comment]
läuft (bis auf max. 100 werte getestet)
