### ISSUE TITLE
Resetten der rechtenTabelle bei "Datei -> Neu" funktioniert nicht

### ISSUE THREAD

**Issue by Bawama** [Schtani/Stichprobe#126]
Die tabelle wird erst gelöscht, wenn nach dem resetten über "datei -> neu" eine weitere Aktion erfolgt (z.b. Eingabe eines neues wertes)

**Comment by Schtani** [comment]
Mögliche Lösung: Im initalize des AdvancedEintragenController hinzufügen:

data.addListener((ListChangeListener<BigDecimal>) (c -> (data.isEmpty() ?loeschenAll() : return)));
