### ISSUE TITLE
Häufigkeittextfeld für 100 zulassen

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#129]
Das Häufigkeitstextfeld für den Wert 100 zulassen. Umso auch 100 Stichproben auf einmal hinzufügen zu können. 

Optimal und zu wünschen wäre eine Kopplung an de.dhbw.vs.stichprobe.utilConstraints.MAX_WERTE

Bei der Gelegenheit kannst du es auch so umstellen, dass bei angelsächsischen Computern, die entsprechende Schreibweise möglich ist. Alternative: nur Deutsche Schreibweise ist möglich und wird immer als Deutsche Schreibweise Interpretiert.

**Comment by ElDiffelo** [comment]
Warum sollte man 100mal die selbse Stichprobe einfügen, wenn maximal 100 zugelassen sind? Das Ergebnis kannst dir im Kopf ausrechnen.

**Comment by Schtani** [comment]
War ein Wunsch der GUI und der Testgruppe. Gibt auch entsprechende Testfälle.

**Comment by ElDiffelo** [comment]
Selbst wenn ich das halbwegs gescheit machen würde, kann ich im XML-File keinen Konstruktor mit Parameter aufrufen.

**Comment by Schtani** [comment]
Richtig. Aber du kannst eine StringProperty hinzufügen welche du im XML setzen könntest ;)
