### ISSUE TITLE
Diagramm Icons austauschen

### ISSUE THREAD

**Issue by ElDiffelo** [Schtani/Stichprobe#140]
Erledige ich, sobald diese fertig sind.

**Comment by dyslexicT** [comment]
hab eben gäng drauf angesprochen, er will sie uns heute abend geben.

**Comment by Schtani** [comment]
Mich haben bereits die erste Entwürfe erreicht. Sobald die Finale Version verfügbar ist, lade ich diese hoch. @ElDiffelo ich gehe davon aus, dass ich die alten Bilder einfach ersetzen kann, oder?

![pie](https://cloud.githubusercontent.com/assets/4836892/6238347/8a973c32-b6fa-11e4-96fa-eaefc2a08b0a.jpg)
![lorenz](https://cloud.githubusercontent.com/assets/4836892/6238346/8a963b8e-b6fa-11e4-982f-b5405ea3c4c4.jpg)
![whatever](https://cloud.githubusercontent.com/assets/4836892/6238348/8ac6d942-b6fa-11e4-881c-5de441538c61.jpg)

**Comment by Schtani** [comment]
Bilder jetzt verfügbar. Und im FIX-Stream. 
![diagrammbarchart_128x128](https://cloud.githubusercontent.com/assets/4836892/6238937/3a3db284-b6ff-11e4-8f1a-c0b53d439c10.png)
![lorenz-128x128](https://cloud.githubusercontent.com/assets/4836892/6238936/3a3dabb8-b6ff-11e4-973c-44a301ea8174.png)
![piediagram_128x128](https://cloud.githubusercontent.com/assets/4836892/6238938/3a40555c-b6ff-11e4-8c3d-45127c0424b0.png)
![verteilung_128x128](https://cloud.githubusercontent.com/assets/4836892/6238939/3a43923a-b6ff-11e4-9100-d138db142d6b.png)

**Comment by ElDiffelo** [comment]
können einfach ersetzt werden
