### ISSUE TITLE
X (rechts oben) im Beenden-Dialog geht nicht

### ISSUE THREAD

**Issue by Bawama** [Schtani/Stichprobe#144]
sollte dieselbe Funktion wie "Abbrechen" haben.

Aufgetreten bei: 2015-02-17-2345-build

**Comment by Schtani** [comment]
Was passiert?

Bawama <notifications@github.com> schrieb am Mi., 18. Feb. 2015 11:23:

**Comment by Bawama** [comment]
nix

**Comment by Schtani** [comment]
Closed mit #146
