### ISSUE TITLE
Standardmäßiges Diagramm

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#148]
# Testfall: 105

## Logischer Testfall:
Standardmäßig wird beim erstmaligen Aufruf das Balkendiagramm angezeigt

## Konkreter Testfall:
Eingabe einer beliebigen Stichprobe, klick auf den Reiter "Grafische Ausgabe"

## Erwartetes Ergebnis:
Es wird das Balkendiagramm angezeigt mit den entsprechenden Werten

## Eingetroffenes Ergebnis:
Dies trifft nicht zu. Wenn ich z.B im Programm bin und eine Stichprobe mir auf der Empirischen Verteilungsfunktion anschaue.
![105_1](https://cloud.githubusercontent.com/assets/4836892/6265618/9d5b138e-b830-11e4-833d-e4085a91cb11.png)

Danach die Werte mit dem Button Alles lösche 
![105_2](https://cloud.githubusercontent.com/assets/4836892/6265621/a3aca162-b830-11e4-9913-1d1f9b058b7c.png)

Daraufhin eine neue Stichprobe eingebe
![105_3](https://cloud.githubusercontent.com/assets/4836892/6265627/aa50edca-b830-11e4-8ee5-97836729468e.png)

Und danach wieder in die Grafische Ansicht wechsle lande ich wieder in der empirischen Verteilungsfunktion. Ich verstehe das Testkonzept folgendermaßen, dass ich bei jeder neuen Stichprobe wieder standardmäßig im Balkendiagramm landen muss.
![105_4](https://cloud.githubusercontent.com/assets/4836892/6265631/add1e490-b830-11e4-8aa7-fad756831ba8.png)

**Gemeldet von:**  ElManu
**Gemeldet am:**  19.02.2015 - 12:08

**Comment by dyslexicT** [comment]
ist das wichtig?
hat das relevanz?

**Comment by Schtani** [comment]
Hab es der Vollständigkeits halber mal aufgenommen. Auch wenn ich sagen würde: 

"works as desgined"

Ich schau mir es aber kurz mal an, welcher Aufwand das wäre. (wegen 2-3 Zeilen Code diskutiere ich nicht drum ;)).

**Comment by Schtani** [comment]
Mit #159 fixed
