### ISSUE TITLE
Anzeige der Lorenzkurve

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#149]
# Testfall: 109 Anzeige der Lorenzkurve

## Stichprobe: 
"3", "4", "5", "5", "5", "6", "6"

## Erwartetes Ergebnis Testkonzept: 
(0 /0), (0.14 / 0.09), (0.28 / 0.21), (0.43 / 0.35), (0.57 / 0.5), (0.71 / 0.65), (0.86 / 0.82) und (1 /1)

## Eingetroffenes Ergebnis: 
Im Schaubild der Lorenzkurve wird der 3 Punkt auf (0,29/0,21) angezeigt.

## Zu klären:
Bitte klären welche Rundung richtig bzw. Falsch ist

## Code:
#9, #81, #91, #100

# Testfall 119
Lorenzkurve 2 Punkt:
Testkonzept (0,33/0,0414) Programm (0,33/0,04)

## Gemeldet via:
https://www.facebook.com/groups/dhbwvs.wwi12c/permalink/909839575703561

**Comment by Schtani** [comment]
# Auszug aus dem Fachkonzept 

Die Lorenzkurve ist ein Polygonzug der alle Punkte `um`und `vm`verbindet.
`um` ist der relative Anteil der ersten `m` Werte an allen `n` Stichprobenwerten, also `m / n`
`vm` ist der relative Anteil der Summe der ersten `m` Werte an der Gesamtsumme aller
Stichprobenwerte .

Weitere führende Informationen: http://www.crashkurs-statistik.de/lorenzkurve/

**Comment by dyslexicT** [comment]
Erster Punkt ist 1 / Anzahl der Werte in der Stichprobe * Position in der Stichprobe
=> 1 / 7 * 2 = 0,285714286... gerundet  0,29 da man bei uns bei 0,5 aufrundet...

**Comment by Schtani** [comment]
Added to Fehlerbeschreibung:
![bug](https://cloud.githubusercontent.com/assets/4836892/6267774/511274ec-b847-11e4-8c42-746a01151a67.PNG)

würde es trotzdem als 'not a bug' deklarieren

**Comment by dyslexicT** [comment]
Da gesagt wurde alle Zahlen - ausgenommen Gini-Koeffizient - auf die 2. Nachkommastelle zu runden versteh ich das problem zum Testfall 119 nicht... Im Test wurde das mit der 2. Nachkommastelle nicht beachtet. Und wenn ich den Wert vom Test Runde kommt das richtige raus.
Wie gesagt, ich sehe maximal einen Fehler darin, dass die Testgruppe den Wert zu genau angegeben hat. => not a bug

**Comment by Schtani** [comment]
Kein Bug, sondern Fehlerhafter Test. Danke @dyslexicT fürs Nachrechnen
![bug](https://cloud.githubusercontent.com/assets/4836892/6272164/dfc7b116-b865-11e4-97a8-0d3fa745093a.PNG)
