### ISSUE TITLE
Mouse-Over Empirische Verteilungsfunktion

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#150]
# Testfall 111: Anzeige der (Punkt-) Koordinaten in einer empirischen Verteilungsfunktion

## Logischer Testfall
Bei der empirischen Verteilungsfunktion werden bei Mouse-Over die Koordinaten der Punkte angezeigt 

## Konkreter Testfall
Eingabe einer Stichprobe mit den Werten "5","17". Nach Eingabe der Stichprobe wird der Reiter "Grafische Ausgabe" aufgerufen und die empirische Verteilungsfunktion (viertes Diagramm von links) ausgewählt

## Erwartetes Ergebnis
In der empirischen Verteilungsfunktion werden bei Mouse-Over die Koordinaten der Punkte angezeigt: 
```
0 für X < 5
0,5 für 5 <= X <17
1 für X >= 17
```
## Testergebnis: 
Bei mir funktioniert das Mouse-Over nicht wenn der erste Strich sich genau auf der X-Achse befindet. Habe es mit drei Stichproben ausprobiert.

## Tester: 

El Manu

## Gemeldet via:

https://www.facebook.com/groups/dhbwvs.wwi12c/permalink/909712089049643

## Assignee:
JP ist ja leider ein `Ghost` User. @soul-reaper  ich hoffe du hast den Skill, dass Problem zu beheben. 

# Testfall 117
Das Mouse Over funktioniert auch bei Punkten auf der Y Achse bei der Empirischen Verteilung nicht.
![bug](https://cloud.githubusercontent.com/assets/4836892/6267633/01190af6-b846-11e4-8c6a-5a56d1ec86bb.PNG)
Wurde zusammen mit ergänzen für Bug #153 gemeldet.
## Gemeldet via:
https://www.facebook.com/groups/dhbwvs.wwi12c/permalink/909834865704032

**Comment by dyslexicT** [comment]
Das ist glaub Absicht... zumal y = 0 ist und x davon abhängt wo der erste Strich ist...

**Comment by Schtani** [comment]
Da es sich um die `Empirische Verteilfunktion` handelt, wäre es cool wenn @SergejL mal darüber schauen könnte und mal seine Einschätzung mitteilen könnte. Bug / No-Bug. (Ich habe da Fachlich nicht wirklich des Know-How).

**Comment by SergejL** [comment]
Der erste Punkt bei y = 0 beginnt theoretisch bei -∞ und geht bis x < (kleinster Strichprobenwert). Für den festen Startpunkt - sowie den End-Punkt bei y = 1 -  wir der durchschnittliche Abstand zwischen den Strichprobenwerten genommen. 

Deswegen wäre eine Anzeige des ersten Punkt bei y = 0 sowie aller End-Punkte irreführend, da diese theoretisch keinen fixen Punkt haben sondern ins unendliche (unendlich minimaler Abschstand) gehen.

**Comment by Schtani** [comment]
In Bug Beschreibung hinzugefügt: 
![bug](https://cloud.githubusercontent.com/assets/4836892/6267652/20506a4a-b846-11e4-851e-24dbb01c9bf5.PNG)

**Comment by Schtani** [comment]
Fachkonzept hat der Ablehnung dieses Issues zugestimmt. Vielen Dank @SergejL für die gute Erklärung.

![not a bug](https://cloud.githubusercontent.com/assets/4836892/6272350/47ed1aaa-b867-11e4-9149-732e060f6a88.PNG)
