### ISSUE TITLE
Abweichungen in der Berechnung

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#153]
# Testfall 114
Stichprobe mit 20 Beobachtungs-Werten.
Positiv, Ganzzahl und Kommazahl.

## logischer Testfall
Es wird eine Stichprobe eingegeben. Die Ergebnisse sind zu überprüfen.

## konkreter Testfall
explizite Stichprobe:
(32, 5, 8, 9.5, 13, 54, 7.8, 50, 69, 70, 80, 21, 33.5, 40, 6, 55, 43, 39.1, 10.3, 90)

z= Mittelwert = 36,81

### Quantil 0,1
**Testkonzept:** `13,8` 
**Programm:** `6,9`

### Mittlere absolute abweichung zu z
**Testkonzept:** `22,24` 
**Programm:** `22,20`

### Standardabweichungen zu s:
**Testkonzept:** `26,79` 
**Programm:** `26,77`

### Varianz s2: 
**Testkonzept:** `717,80` 
**Programm:** `716,77`

### Gini: 
**Testkonzept:** `4` 
**Programm:** `4,0001`
Testkonzept rundet ungenau: -> wontfix

## Gemeldet via:
https://www.facebook.com/groups/dhbwvs.wwi12c/permalink/909818032372382

# Testfall 115

## Stichprobe: 
```
0.5, 14, 30.25, 64, -140, 340, 14, -140, 780, -40.25, 30.25, 99, -113.5, 780, -40.25, -140, 30.25,-140, 780, 340, 780, 3.25, 101.5, -5, -5, -140, -40.25, -5, 64, 14, 340, 30.25
```
### Varianz s2:
**Testkonzept:** `80780,03` 
**Programm:** `80780,34`
Dieser Unterschied beruht auf Rundungsdifferenzen im Testkonzept. Durch Nachrechnen der Varianz durch @S-Marti konnte das Problem behoben werden. 

### Gini 
**Testkonzept:** `entfällt` 
**Programm:** `0,4753`

__siehe #156__

## Gemeldet via:
https://www.facebook.com/groups/dhbwvs.wwi12c/permalink/909822315705287

# Testfall 121

## Stichprobe
`-12, 0, 3.74, 3.74, 88.18`

### Mittlere absolute Abweichung zu z:
**Testkonzept:** `28,732` 
**Programm:** `20,78`

### Gini:
**Testkonzept:** `0,2727` 
**Programm:** `Kein Ergebnis`
zusätzlich fixed in #156 
__Testkonzept fehlerhaft__

## Gemeldet via:
https://www.facebook.com/groups/dhbwvs.wwi12c/permalink/909845672369618

**Comment by Schtani** [comment]
Testfall 115 liefert ähnliche Fehler.

**Comment by dyslexicT** [comment]
![quantil](https://cloud.githubusercontent.com/assets/10848450/6267280/de27b2fc-b842-11e4-8239-d251baf1903c.png)
Nach ein bisschen rumspielen hab ich es geschafft von dem Teil das Quantil 0,1 zu bekommen... ergbnis = 6?
und ich bin jetzt verwirrt

**Comment by SergejL** [comment]
Das Quantile 0,1 kann nicht größer sein als das Quantil 0,25.

Ausszug aus dem Testkonzept:
![image](https://cloud.githubusercontent.com/assets/10756722/6267306/02c5818e-b843-11e4-9088-f10abc2fde92.png)

**Comment by Schtani** [comment]
Fehler von Testfall 116 in Beschreibung hinzugefügt.
![bug](https://cloud.githubusercontent.com/assets/4836892/6267588/914c3afe-b845-11e4-9819-df334e740a19.PNG)

**Comment by S-Marti** [comment]
Ich denke auch, dass wir bis auf das Quantil 0,1 einfach nur Rundungsdifferenzen haben. Vivien ist informiert, sie hat die Nachrichten aber bislang nicht gelesen. An der Berechnung Varianz bei 32 Beobachtungswerten bin ich dran. Melde mich dann erneut.

**Comment by S-Marti** [comment]
Anzeige eines Wertes bei Gini (Testfall 115) sehe ich allerdings als wirklichen Fehler an

**Comment by Schtani** [comment]
Testfall 115 zur Methodenbeschreibung hinzugefügt: 

![bug](https://cloud.githubusercontent.com/assets/4836892/6267846/fc6cd6fc-b847-11e4-95b9-3f017fb53f5b.PNG)

**Comment by S-Marti** [comment]
Berechnung Varianz bei 32 Beobachtungswerten (Testfall 115) ist durch. Rundungsdifferenz konnte beseitigt werden. Bei Berechnung ohne jegliche Zwischen-Rundung durch den Taschenrechner komme ich auch auf "euer" Ergebnis: 80.780,34(...274).

**Comment by Schtani** [comment]
Testfall 117 wird nicht mehr als Fehler eingestuft und daher aus der Beschreibung entfernt: 

![bug](https://cloud.githubusercontent.com/assets/4836892/6268046/c439045c-b849-11e4-8460-e65c6c2a7ded.PNG)

**Comment by Schtani** [comment]
@S-Marti danke für die Berechnung. Ich entferne daher die Zahl aus der Fehlerbeschreibung :+1:

**Comment by dyslexicT** [comment]
Den Testfall 115 konnte ich nachvollziehen...
Wenn Werte eingegeben werden, wird der Gini gleich berechnet. Wird dann irgendwann was negatives eingegeben wird der Gini nicht neu berechnet (Exception), der Feldinhalt aber auch nicht verändert => kommt hier als Gini 0,4753 raus, für die Werte: 0.5, 14, 30.25, 64...

**Comment by Schtani** [comment]
Sry. Das war mein commit 5bfe95461aac50094fe98315bac3e474e8b1c632 . Habe für die Gini berechnung ein Extra Bug erstellt: #155

**Comment by Schtani** [comment]
Testfall 116:
War nicht fehlerhaft.

![bug](https://cloud.githubusercontent.com/assets/4836892/6270237/b36f168e-b858-11e4-815f-a89199e4eb2b.PNG)

**Comment by Schtani** [comment]
zu Testfall 119. @dyslexicT hat in https://github.com/Schtani/Stichprobe/issues/156#issuecomment-75089008 folgendes geschrieben:

> Gini-Koeffizient hab ich mal von Hand nachgerechnet und ich komme auf: 0,4691...
> da ist das Ergebnis des Programms mit 0,4773 deutlich näher dran als das erwartete Ergebnis des 
> Tests mit 0,2727

**Comment by Schtani** [comment]
Testfall 119 aus der Beschreibung entfernt, da dieser korrekt gerechnet wurde. Danke @dyslexicT und @S-Marti für das nachrechnen. 
 
![bug](https://cloud.githubusercontent.com/assets/4836892/6272791/b747a7dc-b86a-11e4-9430-f29506519d04.PNG)

**Comment by Schtani** [comment]
Ich habe mal die Labels angepasst, da ich bezweifel, dass auch nur 1 Fehler durch eine Fehlfunktion des Programmes entstanden ist.

**Comment by Schtani** [comment]
Alle Fehler waren Rechenfehler bzw. ungenauigkeiten im Testkonzept
