### ISSUE TITLE
Fehler in der Gini Berechnung wird nicht angezeigt

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#156]
Der Fehler in der Gini Berechnung wird nicht engezeigt, stattdessen steht der alte wert da.

Dieser Issue entstand aus dem Issue #153.

# Betroffene Testfälle:
* 120
* 121
* 151
* 119

**Comment by Schtani** [comment]
# Fehlerhafter Code
```java

		try {
			giniLabel
					.setText(Converter.convertToString(
							giniBerechnen.giniBerechnen(data),
							Converter.FORMAT_POINT_4));
		} catch (NegativeValueException e) {
			/* Warnmeldung anzeigen, wenn Gini FehlerSchmeißt und Zeit < 0 */
			Long time = exceptionTime.get(e.getMessage());
			time = time == null ? 0L : time;
			if (time + 60000L > System.currentTimeMillis()) {
				exceptionTime.put(e.getMessage(), System.currentTimeMillis());
				log.error("Negativer Gini Wert", e);
				AlertException.showException("Berechnung nicht möglich",
						"Die Berechnung des Ginis ist nicht möglich",
						"Die Liste darf keine negativen Werte enthalten", e);
			}
		} catch (Exception e) {
			log.error("Giniberechnung nicht möglich", e);
		}
```
Es wurde vergessen die Fehlermeldung mit der erzeugten Zeit abzuspeichern. Deshalb wurde diese nie Ausgegeben. Außerdem ist die Zeile `time = time == null ? 0L : time? `; Falsch. Besser wäre `time = time == null ? Long.MAX_VALUE : time;`.

# Lösung
Da das Testkonzept keine Fehlermeldung erwartet diese Zeilen komplett Löschen und einfach einen Leenren Gini, also ` ` ausgeben.

**Comment by Schtani** [comment]
Fix ist mit #158 erstellt.

**Comment by dyslexicT** [comment]
da der Issue was mit Gini Berechnung zu tun hat, schreibe ich mein Senf mal hier rein...
Testfall 119:
Gini-Koeffizient hab ich mal von Hand nachgerechnet und ich komme auf: 0,4691...
da ist das Ergebnis des Programms mit 0,4773 deutlich näher dran als das erwartete Ergebnis des Tests mit 0,2727

**Comment by Schtani** [comment]
Fehler ist mit #158 behoben
