### ISSUE TITLE
Usability "Programm Beenden"

### ISSUE THREAD

**Issue by dyslexicT** [Schtani/Stichprobe#20]
![issue](https://cloud.githubusercontent.com/assets/10848450/6117527/697bbc94-b0b5-11e4-870e-9cc8f14a8e9b.png)
Nach dem Klicken auf den Menüeintrag "Datei" und anschließend auf "Beenden" erscheint derzeit der Dialog, ob man das Programm wirklich beenden will. IMHO dürfte ein Beenden hervorgerufen durch 2 Klicks mit Veränderung der Mauszeigerposition rein zufällig eher selten passieren...
Ich würde daher empfehlen den Dialog an dieser Position zu entfernen und beim Klick auf die Programm schließen Schaltfläche (das "X") anzeigen. Ein versehentlicher Klick auf diese Schaltfläche ist deutlich wahrscheinlicher.

**Comment by Bawama** [comment]
tu es

**Comment by dyslexicT** [comment]
Sehr geilo das ein großteil funktioniert, es hat sich allerdings eine kleine nicht ganz gewünscht Unannehmlichkeit eingeschlichen...
Bei Klick auf "Programm Beenden" und anschließen auf "Cancel" wird das Programm dennoch geschlossen.

**Comment by Bawama** [comment]
tarn es als feature :dancer:

**Comment by Schtani** [comment]
@dyslexicT warum hat es das label wontfix?? Ist doch gefixt.

**Comment by dyslexicT** [comment]
http://www.google.de/imgres?imgurl=http%3A%2F%2Feuf.cc%2Fmedia%2Fbaum.jpg&imgrefurl=http%3A%2F%2Fprezi.com%2Fyolhbjwmtt3c%2Fnatur-und-kultur%2F&h=1130&w=1699&tbnid=vliE1fdXn69TdM%3A&zoom=1&docid=Z-18TU0IaFM_-M&ei=RdbZVNrTJ4mpOr_OgEg&tbm=isch&iact=rc&uact=3&dur=1184&page=1&start=0&ndsp=18&ved=0CE8QrQMwCA

**Comment by ElDiffelo** [comment]
Finde, dass das Beenden überall gleich aussehen sollte. Alternativ zum normalen Dialog, besser ein Abfrage, ob gespeichert werden soll wie z.B. MS Office.

**Comment by Schtani** [comment]
Also auch vor dem Datei -> Beenden eine Frage?

**Comment by ElDiffelo** [comment]
Jo, oder vor beiden eben keine Frage.

**Comment by ElDiffelo** [comment]
Können wir ja auch nochmal mit der projektleitung absprechen, die wollten doch eh nach irgend einer iso prüfen

**Comment by ElDiffelo** [comment]
Evtl. einfach ein Kontrollkäschen rein, wenn man diese gammliege Abfrage nicht mehr haben will, so wie beim beenden von Eclipse.

**Comment by Schtani** [comment]
Abstimmung:
Do: 3
Not Do: 0
Rest Enthaltung
