### ISSUE TITLE
Ästhetik Menüband

### ISSUE THREAD

**Issue by dyslexicT** [Schtani/Stichprobe#23]
![issue](https://cloud.githubusercontent.com/assets/10848450/6117864/1fe8ad8c-b0b8-11e4-873a-232a3fcac2e1.png)
Evtl. hier mal die Dropdown (Pulldown, wth) -Leisten auf eine gleichmäßige Breite bringen und evtl. noch einen kleinen Abstand an der Seite einfügen, damit das nicht so gequetscht aussieht.

**Comment by Schtani** [comment]
Keine Prio.
