### ISSUE TITLE
Eingabefeld Fehler: ignoriert Kommazahlen

### ISSUE THREAD

**Issue by roca91** [Schtani/Stichprobe#30]
Kommazahlen werden ignoriert und als vollständige Zahl übernommen
Bsp.: 5,23 wird zu 523,00

**Comment by Bawama** [comment]
bei buchstabeneingabe wird wert 0 übernommen. absicht?

**Comment by ElDiffelo** [comment]
sind ja noch nicht die numerischen eingabefelder eingebunden. macht auch erst sinn, wenn wir die oberfläche im builder nicht nachbearbeiten müssen.

**Comment by Schtani** [comment]
Fehler: Eingabefeld Fehler: ignoriert Kommazahlen nicht reproduzierbar. @roca91  Bitte weitere Informationen anfügen. (z.B.: Auf welche Systemsprache/Länderzone ist das Gerät gestellt).

![komma zahlen](https://cloud.githubusercontent.com/assets/4836892/6127536/5ef909e4-b12c-11e4-8fe1-ffb2125befc0.PNG). 

Bitte für Text in Eingabefeld ein eigenes Issue erstellen, da diese Issues nur bedingt zumsammenhängen. Ich nehme die Fehlerbeschreibung daher aus dem Titel.

**Comment by roca91** [comment]
Problem kann ich jetzt auch nicht mehr nachvollziehen. Problem scheint wohl ein temporäres Problem gewesen zu sein.
