### ISSUE TITLE
Einzelne Sektionen in der Oberfläche fixieren

### ISSUE THREAD

**Issue by ElDiffelo** [Schtani/Stichprobe#33]
Labels die zusammengehören in Größe/Abstand fixieren, sonst zerreißt es die Texte so bei Vollbild.

**Comment by Schtani** [comment]
Ich habe das bei der Eintragen Seite damit versucht, dass ich eine Tabelle um die Tabelle-Labels gelegt habe, die sich relativ anpasst. Bsp.: `advanced-eintragen.fxml`.

**Comment by ElDiffelo** [comment]
Done
