### ISSUE TITLE
Übernahme der eingegebenen Werte mit "Enter" in Tabellen

### ISSUE THREAD

**Issue by Bawama** [Schtani/Stichprobe#34]
gilt für:
- Felder "Wert" und "Häufigkeit" (Feld Häufigkeit mit "1" vorbelegt, dann reicht auch schon Enter im Feld "Wert" zur Übernahme)
- Button "Einfügen"

**Comment by Schtani** [comment]
Ist eigentlich als Default Button gesetzt. Ka warum es nicht geht. Müsst jemand sich tiefer mit beschäftigen. Evt. ein Listener draufsetzen
