### ISSUE TITLE
30 verschieden Werte, 100 insgesamt

### ISSUE THREAD

**Issue by ElDiffelo** [Schtani/Stichprobe#35]
Kundenwunsch, dass man max. 30 verschieden Werte, 100 insgesamt eintragen kann. Falls mehr wird eine Fehlermeldung angezeigt.

**Comment by Schtani** [comment]
@Bawama Ist das Logik oder gehört es nicht eher zur GUI? Bzw. GUI-Logik? 

Die Frage ist wo dieses Feature implementiert werden soll:
* Reine GUI Prüfung
* Services schmeißen Exceptions. GUI fängt diese
* Wir überlassen Spring die Prüfung, dieser schmeißt die Exceptions und die GUI fängt diese.

Ich würde aktuell zu Lösung 3 tendieren, oder habe ich den Issue Falsch verstanden?

**Comment by ElDiffelo** [comment]
Keine Gui, sondern Datenhaltung.
