### ISSUE TITLE
Tabellen Sortieren duch klick auf "werte" - verhalten beim 3. Klick

### ISSUE THREAD

**Issue by Bawama** [Schtani/Stichprobe#36]
pfeil verschwindet, werte bleiben sortiert wie beim 2. klick. Logik dahinter?

**Comment by Schtani** [comment]
Sortierung kein expliziter Kundenwunsch, wird erst in V2 geschlossen.

**Comment by Schtani** [comment]
Mit #97 schon früher geschlossen.
