### ISSUE TITLE
Alert auslagern

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#37]
Aktuell werden alle Alerts manuell mittels eines Alert Objects erzeugt. 
Diese sollten wir in eine Util Klasse mit statischen Methoden, ähnlich der AlertException auslagern. 

Grund: Sonst haben diese Alert Fenster später kein Favicon.

**Comment by Schtani** [comment]
hängt mit #8, da dass Fav Icon gesetzt werden muss.

**Comment by soul-reaper** [comment]
Alle Dialoge brauchen das favicon
