### ISSUE TITLE
Eingabefeld Fehler: bei Buchstaben wird wert "0" übernommen

### ISSUE THREAD

**Issue by Bawama** [Schtani/Stichprobe#39]
betrifft feld "wert" (bei "häufigkeit" wird beim wert "0" logicherweise nichts angezeigt, mögliche umsortierung der tabelle wird jedoch möglich (pfeile neben "wert" in tabelle) )

**Comment by ElDiffelo** [comment]
Evtl. mit #26 behoben

**Comment by SergejL** [comment]
Es wird der Wert 0 in die Tabelle eingefügt wenn das Feld "Wert" leer ist und auf Einfügen geklickt wird.

**Comment by dyslexicT** [comment]
cause of feautures...

**Comment by Schtani** [comment]
gelöst @Bawama - Falls nicht reopen
