### ISSUE TITLE
Löschen Button funktioniert nicht

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#7]
Der Löschen Button hat keine Funktion:
Frage: Wie soll die genau Funktion des Löschens Button aussehen:
* Soll die zuletzt gesehen Zeile gelöscht werden (Dh. bei absolut -> alle)
* Immer 1 entsprechender Einzelwert gelöscht werden
* Immer 1 entsprechender Absoultwert (ink. aller einzelwerte) gelöscht werden
* Die Auswahl ob ein Einzel/Mehrfachwert gelöscht werden soll, erfolgt anhand des ausgewählten Radio Buttons.

![loschen](https://cloud.githubusercontent.com/assets/4836892/6111558/18e9997a-b08a-11e4-8d8e-add32ce43635.png)

Am schwersten umzusetzen ist vermutlich das erste, das letzte wird vermutlich am leichtesten sein.

Ich würde aktuell zu dem letzten tendieren. Wie sieht es bei euch aus?

Sollen wir diese Frage an die GUI Konzeptgruppe weiterleiten?

**Comment by dyslexicT** [comment]
Ja zur letzten Frage, soll sich die GUI gruppe damit rumschlagen...

Ne ich würde die derzeit ausgewählte Zeile löschen. Evtl. noch nen weiteren Button dazu der alles Löscht...

**Comment by Schtani** [comment]
@dyslexicT  mit derzeit ausgewählt meinst du die letzte ausgewählte Spalte. Oder kannst du auf dem Screenshot erkennen, welche derzeit ausgewählt ist?

**Comment by dyslexicT** [comment]
@Schtani damit meinte ich jeweils die Grau hervorgehobene Zeile, müsste nur ein Mechanismus eingebaut werden, der bei auswahl einer Zeile links die betreffende Rechts auswählt, bzw. anders herum auch.

**Comment by Schtani** [comment]
Created Branch `DeleteButton` for this function.

**Comment by Schtani** [comment]
Fixed in #15
