### ISSUE TITLE
Gini-Koeffizient Anzeige 4 Nachkommastellen

### ISSUE THREAD

**Issue by dyslexicT** [Schtani/Stichprobe#74]
Der Gini-Koeffizient kann maximal den Wert 1 haben. Daher ist bei einer Verteilung von sehr niedrigen Werten dieser Koefizient sehr greing. Im Testfall (aus dem Vorlesungsbuch Hr. Heinrich) ist dieser lediglich bei 0,0458. Deshalb bitte erweitern auf 4 Nachkommastellen.

**Comment by Schtani** [comment]
Close mit #76
