### ISSUE TITLE
Empirischen Verteilungsfunktion

### ISSUE THREAD

**Issue by SergejL** [Schtani/Stichprobe#77]
Wird die Anzeige des 
E(x) = 0	für x < (kleinster Wert) 
und 
E(x) = 1 für x ≥ (größter Wert) 
im Diagramm benötigt? 
Wenn ja, bis welchen bereich soll x gehen?
Müsste vom Fachkonzept-Team oder von Herr Grass beantwortet werden.

**Comment by Schtani** [comment]
Frage ist an Fachkonzept Gruppe weitergeleitet.

**Comment by Schtani** [comment]
x-Achse geht vom kleinsten zum größten Wert + 5%.

**Comment by Schtani** [comment]
E(x) = 0 für x < (kleinster Wert)  - :+1: OK
E(x) = 1 für x ≥ (größter Wert) 

1. Punkt ist der kleinste, davor kommt ein "Balken" / Strich auf der X - Achse.

**Comment by Schtani** [comment]
Super korrekt wäre vorne ein ausgefüllter Punk und hinten ein leerer Kreis.

**Comment by Schtani** [comment]
Aktuelle fehlt der oberste und unterste Balken. :!:

**Comment by Schtani** [comment]
sie dazu auch https://www.facebook.com/groups/dhbwvs.wwi12c/906087289412123/

**Comment by SergejL** [comment]
Aus dem Fachkonzept:
> Um eine einheitliche Darstellung zu gewährleisten, wird festgelegt, dass der Startpunkt der Funktion um 5% kleiner sein soll als der niedrigste Stichprobenwert. Die Funktion endet entsprechend beim größten Stichprobenwert plus 5%. 

-5% von kleinsten bzw. +5% vom größten Wert macht für mich kaum Sinn. Z.B. wenn der kleinste Wert 0 ist. Überhaupt würde dadurch der erste und letzte Strich unterschiedlich lang sein.

Wenn wir 5% von etwas nehmen dann lieber vom Abstand des kleinsten Wertes zum größten Wert oder einem anderen fixen Wert (Standard Abweichung?).

**Comment by ElDiffelo** [comment]
sieht man den strich, wenn er dicker ist?

**Comment by Schtani** [comment]
Mach es so wie es passt. Bitte irgendwo dokumentieren.

SergejL <notifications@github.com> schrieb am Do., 12. Feb. 2015 21:23:

**Comment by ElDiffelo** [comment]
kann es sein, das der erste und letzte strich garnicht gezeichnet werden? wenn ich die y-Achse von -0,1 bis 1,1 zeichnen lasse sieht man die beide auch nicht. Siehe Screenshot:

![test](https://cloud.githubusercontent.com/assets/10763321/6179059/990f9522-b315-11e4-95d0-35deb8d863a2.PNG)

**Comment by ElDiffelo** [comment]
Eventuell der Liste noch die Werte 0 und 1 manuell hinzufügen? Die kommen in der Berechnung ja nie raus..

**Comment by SergejL** [comment]
> kann es sein, das der erste und letzte strich garnicht gezeichnet werden? wenn ich die y-Achse von -0,1 bis 1,1 zeichnen lasse sieht man die beide auch nicht. Siehe Screenshot:

richtig, die Striche werden nicht gezeichnet (habe ich raus genommen), da nicht klar ist wie lang diese sein sollen.

**Comment by ElDiffelo** [comment]
Okay, dann hab ich wohl das Problem nicht verstanden.

**Comment by ElDiffelo** [comment]
Falls du die größe der Punkte bearbeiten willst, musst du beachten, dass die runden Punkte unsere Nodes fürs Hovern sind. Die könnte man auch unsichtbar machen, dann sieht man auf der lorenzkruve aber auch keine punkte mehr.

**Comment by ElDiffelo** [comment]
Sieht schon irgendwie blöd aus, wenns nicht mehr bei 0 anfängt. Außerdem funktioniert der Hover beim ersten Wert nicht.

**Comment by SergejL** [comment]
So würde es aussehen wenn das Diagramm bei 0 anfängt und überwiegend hohe Werte in der Stichprobe stehen:
![image](https://cloud.githubusercontent.com/assets/10756722/6214608/04197c34-b5fa-11e4-9c22-47f6ece3eebe.png)
Finde ich nicht so gut.

Den Hover sieht man nicht, da er unterhalb  der Diagrammsbegrenzung auftaucht. Kann man da was machen?

Überhaupt, der Hover beim End-Punkt jeder Linie ist eher unpraktisch, da das Ende der Linie unter dem nächsten wert liegen sollte (x<nächster Wert). Durch den Hover sieht man aber das der Punkt genau darauf liegt. Könnte man die Anzeige der Koordinate am End-Punkt ausschalten aber die formatierung Node.visible = false behalten?

**Comment by ElDiffelo** [comment]
Könnte man ausschalten oder einfach garkeine setzen.

**Comment by ElDiffelo** [comment]
kann ich das direkt in der#77 ändern und einchecken?

**Comment by Schtani** [comment]
Blöde Frage: Auf welchen Branche arbeitet ihr? Bzw. Könnt ihr das alles mal
auf einen Branche z.B.: FIX-77-Empirische-Verteilungsfunktion commiten /
pushen?

**Comment by ElDiffelo** [comment]
Habe ich gerade getan.

**Comment by ElDiffelo** [comment]
Schaut mal drauf, ob es so besser ist. Wenn die Node 0/0 keinen Hover hat ist das ja nocht unbedingt schlimm. Mich stört nur, dass sie immer hinter der 0 anfängt.

**Comment by ElDiffelo** [comment]
#141

**Comment by ElDiffelo** [comment]
Find das sieht so eigentlich schon ganz geil aus. Warum die erste Node jetzt immer noch kein Label bekommt versteh ich zwar nicht wirklich, da Y ja kleiner 0.2 ist, aber passt schon.

**Comment by Schtani** [comment]
Soll ich mal einen Stand bauen, und die Fachkonzeptgruppe fragen, ob die Diagramme jetzt passen?

**Comment by ElDiffelo** [comment]
Bau mal. Und frag bei der Gelegenheit auch nach den Symbolen für die Diagramme.

**Comment by Schtani** [comment]
https://www.facebook.com/groups/dhbwvs.wwi12c/permalink/908488982505287/

**Comment by Schtani** [comment]
Da innerhalb der letzten 24 Stunden keine negative Rückmeldung aus der Fachkonzept Gruppe mich erreicht hat, werde ich diesen Issue mal schließen. @SergejL Vielen Dank für das Durchhaltevermögen :wink: :+1: . Bei Bedarf müssen wir in halt wieder öffnen, wenn die Tester damit nicht zufrieden seien sollten. :facepunch:
