### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Schtani** [Schtani/Stichprobe#8]
Aktuell fehlt noch ein Favicon. Weiß jemand wer ein entsprechend erstellt hat?

optimal wären folgende Auflösungen:
* 16x16 png
* 32x32 png
* 48x48 png
* 64x64 png

**Comment by dyslexicT** [comment]
Könnte was suchen / bauen... hab nur keine Idee... vllt. weiß der Gäng was?

**Comment by Schtani** [comment]
Habe die Nachricht ihn mal via WhatsApp weitergeleitet.

**Comment by soul-reaper** [comment]
Gäng +1

**Comment by ElDiffelo** [comment]
Done
