### ISSUE TITLE
Speichern abbrechen

### ISSUE THREAD

**Issue by SergejL** [Schtani/Stichprobe#80]
Beim Abbrechen des Speichern-Dialogs nach klicken auf das X oben Rechts wird die Anwendung beendet. Das gleiche passiert nicht, wenn das Speichern-Dialog über Datei > Beenden > Speichern geöffnet wurde.

**Comment by Schtani** [comment]
Wird verschoben und daher geschlossen

**Comment by Schtani** [comment]
Duplicate mit #127

**Comment by Schtani** [comment]
Geschlossen mit #136
