### ISSUE TITLE
Gini / Lorenzkurve

### ISSUE THREAD

**Issue by soul-reaper** [Schtani/Stichprobe#9]
Für den Ginikoeffizienten werden die Werte benötigt, welche bei der Lorenzkurve angezeigt werden.
Daher der Vorschlag einen Service zu implementieren, der diese zurückgibt. Dafür würde ich ein Datenobjekt nehmen, welches ums und vms kapselt.

**Comment by Schtani** [comment]
Finde ich gut

**Comment by dyslexicT** [comment]
#62 Gini erledigt. Lorenzkurve muss noch Implementiert werden

**Comment by Bawama** [comment]
gini läuft noch nicht.

**Comment by dyslexicT** [comment]
Lorenz nehm ich jetzt in Angriff

**Comment by dyslexicT** [comment]
Fehler gelöst durch #81

**Comment by dyslexicT** [comment]
erster Teil in #91 realisiert.

**Comment by dyslexicT** [comment]
done in #100
