### ISSUE TITLE
Modalwert zeigt Werte aus Tabelle an

### ISSUE THREAD

**Issue by SergejL** [Schtani/Stichprobe#99]
![image](https://cloud.githubusercontent.com/assets/10756722/6140533/5f6f18f6-b199-11e4-835e-c2931bf6a5af.png)

**Comment by Schtani** [comment]
Bsp.: 12;24;34

**Comment by Bawama** [comment]
fehler nur bei mehr als 2 werten (modalwert kann u.u. 2 werte enhalten, bei nur 2 werten IMMER beide werte modalwerte)

**Comment by SergejL** [comment]
kein Fehler. Modalwert zeigt den Wert mit der höchsten Häufigkeit. Bei mehreren Werten mit der gleichen Häufigkeit werden diese alle angezeigt.
